name: Build APK

on:
  push:
    branches:
      - master  # Ou outro branch que você queira monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential libssl-dev libffi-dev python3-dev
        pip3 install --upgrade cython virtualenv
        sudo apt install -y libtool libffi-dev libssl-dev
        sudo apt install -y build-essential python3-kivy
        pip3 install kivy
        pip3 install buildozer

    - name: Build APK
      run: |
        buildozer init
        buildozer android debug
      working-directory: .

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: ./bin/*.apk
